import React from "react";

export const FAQ = () => {
  return (
    <div>
      PREGUNTAS FRECUENTES SOBRE ENTREGAS DE PEDIDOS DE MANGAS, SALIDA DE NUEVOS
      PRODUCTOS/MANGAS / RESTOCK DE PRODUCTOS/MANGAS, SUCURSALES DONDE RETIRAR O
      COMPRAR PERSONALMENTE, INFORMACIÓN/OBJETIVO SOBRE NOSOTROS
    </div>
  );
};
